"""
Django settings for ElectionCampaign project.

Generated by 'django-normaladmin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-rher1htozqaa2+w=@_wp$_px_jp^a0^*7toceejb2h+ut_zn&4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
          'django.contrib.admin',
          'django.contrib.auth',
          'django.contrib.contenttypes',
          'django.contrib.sessions',
          'django.contrib.messages',
          'django.contrib.staticfiles',
          'corsheaders',
          'drf_yasg',
          'rest_framework',
          'electionadmin',
]

CORS_ORIGIN_ALLOW_ALL = True

MIDDLEWARE = [
          'corsheaders.middleware.CorsMiddleware',
          'django.middleware.security.SecurityMiddleware',
          'django.contrib.sessions.middleware.SessionMiddleware',
          'django.middleware.common.CommonMiddleware',
          'django.middleware.csrf.CsrfViewMiddleware',
          'django.contrib.auth.middleware.AuthenticationMiddleware',
          'django.contrib.messages.middleware.MessageMiddleware',
          'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ElectionCampaign.urls'

TEMPLATES = [
          {
                    'BACKEND': 'django.template.backends.django.DjangoTemplates',
                    'DIRS': [],
                    'APP_DIRS': True,
                    'OPTIONS': {
                              'context_processors': [
                                        'django.template.context_processors.debug',
                                        'django.template.context_processors.request',
                                        'django.contrib.auth.context_processors.auth',
                                        'django.contrib.messages.context_processors.messages',
                              ],
                    },
          },
]

WSGI_APPLICATION = 'ElectionCampaign.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
          'default': {
                    'ENGINE': 'django.db.backends.mysql',
                    'NAME': 'election_campaign',
                    'USER': 'root',
                    'PASSWORD': '1234',
                    'HOST': 'localhost',
                    'PORT': '3306',
          }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
          {
                    'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
          },
          {
                    'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
          },
          {
                    'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
          },
          {
                    'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
          },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
# STATIC_ROOT = BASE_DIR / "staticfiles"

# New configuration for admin photos
MEDIA_ROOT_ADMIN = os.path.join(BASE_DIR, 'Admin_Images')
MEDIA_URL_ADMIN = '/Admin_Images/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
